apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demoapp-ingress
spec:
  rules:
  - host: demoapp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demoapp-service
            port:
              number: 8080

